catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'
urlpatterns = [
	url(r'^$', views.catalog_home, name="home"),
	url(r'^(?P<catalog_id>[\d]+)$', views.catalog_detail, name='detail'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('default_app.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
from django.db import models

class  Catalog(models.Model):
	title = models.CharField(max_length=150)
	image = models.ImageField(upload_to='catalog_images', blank=True)
	description = models.TextField()

	
	def __str__(self):
		return self.title

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Catalog
#from django.http import HttpResponse


def catalog_home(request):
	catalog_list = Catalog.objects.all()
	paginator = Paginator(catalog_list, 4)

	page = request.GET.get('page')
	try:
		catalog = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		catalog = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		catalog = paginator.page(paginator.num_pages)
	# Redirect to main rout if Geat query is ?page=1
	if page == '1':
		return redirect('catalog:home', permanent=True)

	context = {
		'page_header': 'Catalog page',
		'catalog': catalog,
	}
	return render(request, 'catalog/catalog.html', context)

def catalog_detail(request, catalog_id):
	catalog_item = get_object_or_404(Catalog, pk=catalog_id)
	context = {
		'page_header': catalog_item.title,
		'catalog_item': catalog_item,
	}

	return render(request, 'catalog/catalog_detail.html', context)

catalog/templates/catalog/catalog.html
{% extends 'base.html' %}


{% block content %}

	{% for catalog_item in catalog %}
		<div>
			<h2><a href="{% url 'catalog:detail' catalog_item.id %}">{{ catalog_item.title }}</a></h2>
			<div>
				{{ catalog_item.description|truncatechars:200 }}
			</div>
		</div>
	{% endfor %}

    <div class="text-center">
        <ul class="pagination">
            {% if catalog.number > 1 %}
                <li><a href="?page=1">&laquo; First page</a> </li>
            {% else %}
                <li class="disabled"><a href="">&laquo; First page</a></li>
            {% endif %}

            {% if catalog.has_previous %}
                <li><a href="?page={{ catalog.previous_page_number }}">&laquo; Prev></a></li>
            {% else %}
                <li class="disabled"><a href="">&laquo; Prev</a> </li>
            {% endif %}

            {% if catalog.number > 1 %}
                {% for page in catalog.paginator.page_range %}
                    <li class="{% if catalog.number == page %}active{% endif %}">
                        <a href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endfor %}
            {% endif %}

            {% if catalog.has_next  %}
                <li><a href="?page={{ catalog.next_page_number }}">Next &raquo;</a></li>
            {% else %}
                <li class="disabled"><a href="">Next &raquo;</a></li>
            {% endif %}

            {% if catalog.number < catalog.paginator.num_pages %}
                <li><a href="?page={{ catalog.paginator.num_pages }}">Last page &raquo;</a></li>
            {% else %}
                <li class="disabled"><a href="">Last page &raquo;</a> </li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

catalog/templates/catalog/catalog_detail.html
{% extends 'base.html' %}


{% block content %}

	<div>
		<a class="btn btn-primary" href="{% url 'catalog:home' %}">&larr; Назад в категорию</a><br><br>
	</div>

	<div>
	 	{{ catalog_item.description }}
	</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{% if page_header %}{{ page_header}} | {% endif %}Django sandbox project</title>
	
	<script type="https://cdn.jsdelivr.net/g/jquery@3.1.0,bootstrap@3.3.7"></script>

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.7/css/bootstrap.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

	<img src="{% static 'images/icon-touch.e4872c4da341.png' %}" alt="">

	<div class="container">

		{% if page_header %}
		<div class="page-header">
			<h1>{{ page_header }}</h1>
		</div>
		{% endif %}

		{% block content %} {%  endblock %}
	</div>
	
	

</body>
</html>

templates/default_app/home.html
{% extends 'base.html' %}


{% block content %} 


		{% for cat_item in catalog %}
		<div>
			<h3>{{ cat_item.title }}</h3></li>
			<div>{{ cat_item.description}}</div>
		</div>
		{% endfor %}
		

{% endblock %} 